### ISSUE TITLE
[Feature Request] Allow presets to be configured via YAML file

### ISSUE THREAD

**Issue by rigrassm** [AlphaConsole/AlphaConsoleElectron#12]
Was just thinking it would be nice to be able to manually edit presets using YAML configuration files rather than having to manually edit the config.json or use the UI.

Example use case would be wanting to have a base configuration that you can use as a template for making multiple different presets out of.

Another added benefit would be that users could then easily share presets with each other by sending them their config file.

Eventually, an interface for importing the configurations could be added to the UI as well but initially just being able to drop the configuration files into a directory that gets autoloaded would work just fine.

**Comment by burnss9** [comment]
I don't see any benefit of switching to YAML. Especially since the DLL uses Json already. I don't know why you'd be manually editing the config.json to be honest because the UI is basically made just to do that for you. You can always make changes yourself and use your version of course. The presets array in the config.json is not used at all by the DLL - whenever you select a preset it just copies that preset into the "Items" property of the config.json so you can do whatever you like as long as that gets set properly.

**Comment by Barbosicks** [comment]
Why would you want to manually edit a YAML file and not a JSON file? makes 0 sense.

**Comment by shadoxxhd** [comment]
@rigrassm you can ofc easily code your own json <-> yaml converter
